[project]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["NeonCore", "NeonCore.managers", "NeonCore.game_maps", "NeonCore.npc_behavior", "NeonCore.story_modules", "NeonCore.utils"]

[project.optional-dependencies]
dev = ["bandit"]
