name: Python Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install black pyright ruff

      - name: Run Black
        run: black . --check

      - name: Run Pyright
        run: pyright

      - name: Run Ruff
        run: ruff check .

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
